# Enable preview features.
preview = false

# Allow lines to be as long as ...
line-length = 100

# Source: https://docs.astral.sh/ruff/rules
# E4, E7, E9, B - is default rules
[lint]
select = [
    # pycodestyle
    "E", "W",
    # Pyflakes
    "F",
    # isort
    "I",
    # pep8-naming
    "N",
    # pyupgrade
    "UP",
    # Refactor
    "R",
    # flake8-bugbear
    "B",
    # flake8-annotations
    "ANN",
    # flake8-async
    "ASYNC",
    # flake8-bandit
    "S",
    # flake8-builtins
    "A",
    # flake8-commas
    "COM",
    # flake8-comprehensions
    "C4",
    # flake8-datetimez
    "DTZ",
    # flake8-debugger
    "T10",
    # flake8-import-conventions
    "ICN",
    # flake8-implicit-str-concat
    "ISC",
    # flake8-logging
    "LOG",
    # flake8-logging-format
    "G",
    # flake8-pie
    "PIE",
    # flake8-print
    "T20",
    # flake8-pyi
    "PYI",
    # flake8-pytest-style
    "PT",
    # flake8-quotes
    "Q",
    # flake8-raise
    "RSE",
    # flake8-return
    "RET",
    # flake8-slots
    "SLOT",
    # flake8-simplify
    "SIM",
    # flake8-tidy-imports
    "TID",
    # flake8-type-checking
    "TC",
    # flake8-gettext
    "INT",
    # flake8-unused-arguments
    "ARG",
    # flake8-use-pathlib
    "PTH",
    # flake8-todos
    "TD",
    # flake8-fixme
    "FIX",
    # Pylint
    "PL",
    # tryceratops
    "TRY",
    # Perflint
    "PERF",
    # refurb
    "FURB",
    # McCabe complexity: https://pypi.org/project/mccabe/
    "C90", 
    # Ruff
    "RUF"
]

ignore= [
    "COM812"  # 	missing-trailing-comma: https://docs.astral.sh/ruff/rules/missing-trailing-comma/
]

[lint.mccabe]
# Flag errors (`C901`) whenever the complexity level exceeds 10.
max-complexity = 10

[lint.isort]
force-wrap-aliases = true
combine-as-imports = true
lines-between-types = 1
