name: lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Ruff version
        run: uv run ruff --version

      - name: Run lint
        run: uv run ruff check

      - name: Run format
        run: uv run ruff format --check --diff && uv run ruff check --select I
