name: lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version

      - name: Install uv
        run: pipx install uv

      - name: Install dependencies
        run: uv install --groups default dev

      - name: Ruff version
        run: uv run ruff --version

      - name: Run lint
        run: uv run ruff check

      - name: Run format
        run: uv run ruff format --check --diff && uv run ruff check --select I
