name: Quality Checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  regression:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Ruff version
        run: uv run ruff --version

      - name: Run lint
        run: uv run ruff check

      - name: Run format
        run: uv run ruff format --check --diff && uv run ruff check --select I

      - name: Mypy version
        run: uv run mypy --version

      - name: Mypy check
        run: uv run mypy .

      - name: Unit tests
        run: uv run pytest .
