name: Quality Checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  regression:
    runs-on: ubuntu-24.04
    timeout-minutes: 2
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v10.2.0

      - name: Install Task
        uses: go-task/setup-task@v2

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Ruff version
        run: uv run ruff --version

      - name: Run lint
        run: task lint

      - name: Run format
        run: task format

      - name: Mypy version
        run: uv run mypy --version

      - name: Mypy check
        run: task mypy

      - name: Pytest version
        run: uv run pytest --version

      - name: Unit tests
        run: task test
